---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cache.kloudlite.io
  resources:
  - loadbalancers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.kloudlite.io
  resources:
  - loadbalancers/finalizers
  verbs:
  - update
- apiGroups:
  - cache.kloudlite.io
  resources:
  - loadbalancers/status
  verbs:
  - get
  - patch
  - update
