apiVersion: cache.kloudlite.io/v1alpha1
kind: Loadbalancer
metadata:
  labels:
    app.kubernetes.io/name: loadbalancer
    app.kubernetes.io/instance: loadbalancer-sample
    app.kubernetes.io/part-of: loadbalancer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: loadbalancer
  name: loadbalancer-sample
  namespace: bikash
spec:
  # TODO(user): Add fields here
